// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:26096' | (string & {});
};

export type ComponentMap = {
    templateId: number;
    templateAlias: string;
    name: string;
    parameters: string;
    tagHelper: boolean;
};

export type ContentItem = {
    id: number;
    udi: string;
    alias: string;
    name: string;
    icon: string;
    parentId: number;
    level: number;
    trashed: boolean;
    path: string;
    createDate: string;
    updateDate: string;
    creatorId: number;
    creatorName: string;
    updaterId: number;
    updaterName: string;
    culture: string;
};

export type ContentTags = {
    id: number;
    udi: string;
    alias: string;
    name: string;
    icon: string;
    type: string;
    tags: Array<Tag>;
};

export type ContentTypeData = {
    id: number;
    udi: string;
    name: string;
    alias: string;
    isOpen: boolean;
    icon: string;
    description: string;
    isMaster: boolean;
    hasCompositions: boolean;
    selected: boolean;
};

export type ContentTypeMap = {
    id: number;
    udi: string;
    name: string;
    alias: string;
    isOpen: boolean;
    icon: string;
    description: string;
    isMaster: boolean;
    hasCompositions: boolean;
    selected: boolean;
    templates: Array<TemplateMap>;
    properties: Array<PropertyTypeMap>;
    compositionProperties: Array<PropertyTypeMap>;
    allProperties: Array<PropertyTypeMap>;
    compositions: Array<ContentTypeData>;
    propertyGroups: Array<string>;
    hasTemplates: boolean;
    isListView: boolean;
    allowedAtRoot: boolean;
    isComposition: boolean;
    isElement: boolean;
    variesBy: ContentVariationModel;
    variesByCulture: boolean;
    createDate: string;
};

export const ContentVariationModel = {
    NOTHING: 'Nothing',
    CULTURE: 'Culture',
    SEGMENT: 'Segment',
    CULTURE_AND_SEGMENT: 'CultureAndSegment'
} as const;

export type ContentVariationModel = typeof ContentVariationModel[keyof typeof ContentVariationModel];

export type DataTypeMap = {
    id: number;
    udi: string;
    name: string;
    alias: string;
    isOpen: boolean;
    dbType: string;
    isUsed: boolean;
    updateDate: string;
};

export type Diagnostic = {
    key: string;
    value: string;
};

export type DiagnosticGroup = {
    id: number;
    title: string;
    sections: Array<DiagnosticSection>;
};

export type DiagnosticSection = {
    heading: string;
    diagnostics: Array<Diagnostic>;
};

export type DiagnosticsConfig = {
    groupsToHide: Array<string>;
    sectionsToHide: Array<string>;
    keysToRedact: Array<string>;
};

export const EventMessageTypeModel = {
    DEFAULT: 'Default',
    INFO: 'Info',
    ERROR: 'Error',
    SUCCESS: 'Success',
    WARNING: 'Warning'
} as const;

export type EventMessageTypeModel = typeof EventMessageTypeModel[keyof typeof EventMessageTypeModel];

export type GodModeConfig = {
    featuresToHide: Array<string>;
    diagnostics: DiagnosticsConfig;
};

export type ItemBase = {
    id: number;
    udi: string;
    name: string;
    alias: string;
    isOpen: boolean;
};

export type Lang = {
    id: number;
    name: string;
    culture: string;
};

export type MediaMap = {
    id: number;
    udi: string;
    name: string;
    alias: string;
    isOpen: boolean;
    ext: string;
    type: string;
    size: number;
    createDate: string;
    updateDate: string;
    path: string;
};

export type MemberGroupModel = {
    id: number;
    name: string;
};

export type MemberModel = {
    id: number;
    username: string;
    name: string;
    email: string;
    createDate: string;
    udi: string;
};

export type NameValue = {
    name: string;
    value: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type NuCacheItem = {
    id: number;
    data: string;
    title: string;
    createDate: string;
};

export type Page1 = {
    currentPage: number;
    totalPages: number;
    totalItems: number;
    itemsPerPage: number;
    items?: Array<ContentItem> | null;
};

export type PartialMap = {
    templateId: number;
    templateAlias: string;
    name: string;
    path: string;
};

export type PropertyTypeMap = {
    id: number;
    udi: string;
    name: string;
    alias: string;
    isOpen: boolean;
    editorAlias: string;
    description: string;
    editorId: number;
    variesBy: string;
    supportsPublishing: boolean;
    storageType: string;
};

export type RegisteredService = {
    name: string;
    namespace: string;
    fullName: string;
    isPublic: boolean;
    implementName: string;
    implementNamespace: string;
    implementFullName: string;
    lifetime: string;
};

export type ServerResponse = {
    message: string;
    responseType: ServerResponseType;
    readonly response: string;
};

export const ServerResponseType = {
    SUCCESS: 'Success',
    ERROR: 'Error',
    WARNING: 'Warning'
} as const;

export type ServerResponseType = typeof ServerResponseType[keyof typeof ServerResponseType];

export type Tag = {
    text: string;
    group: string;
    id: number;
    nodeCount: number;
    culture: string;
};

export type TagMapping = {
    key: string;
    tag: Tag;
    content: Array<ContentTags>;
    culture: string;
};

export type TemplateMap = {
    id: number;
    udi: string;
    name: string;
    alias: string;
    isOpen: boolean;
    path: string;
    isDefault: boolean;
};

export type TemplateModel = {
    id: number;
    udi: string;
    name: string;
    alias: string;
    isOpen: boolean;
    virtualPath: string;
    createDate: string;
    isMaster: boolean;
    parents: Array<TemplateModel>;
    path: string;
    masterAlias: string;
    filePath: string;
    hasCorrectMaster: boolean;
    layout: string;
    partials: Array<PartialMap>;
    viewComponents: Array<ComponentMap>;
};

export type TypeMap = {
    module: string;
    assembly: string;
    name: string;
    namespace: string;
    baseType: string;
    loadableName: string;
    isUmbraco: boolean;
};

export type UsageModel = {
    id: number;
    nodeCount: number;
    description: string;
    alias: string;
    icon: string;
    guidType: string;
    readonly type: string;
};

export type ServerResponseWritable = {
    message: string;
    responseType: ServerResponseType;
};

export type UsageModelWritable = {
    id: number;
    nodeCount: number;
    description: string;
    alias: string;
    icon: string;
    guidType: string;
};

export type ClearUmbracoCacheData = {
    body?: never;
    path?: never;
    query?: {
        cache?: string;
    };
    url: '/umbraco/god-mode/api/v1/ClearUmbracoCache';
};

export type ClearUmbracoCacheResponses = {
    /**
     * OK
     */
    200: ServerResponse;
};

export type ClearUmbracoCacheResponse = ClearUmbracoCacheResponses[keyof ClearUmbracoCacheResponses];

export type CopyDataTypeData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/umbraco/god-mode/api/v1/CopyDataType';
};

export type CopyDataTypeResponses = {
    /**
     * OK
     */
    200: ServerResponse;
};

export type CopyDataTypeResponse = CopyDataTypeResponses[keyof CopyDataTypeResponses];

export type DeleteTagData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/umbraco/god-mode/api/v1/DeleteTag';
};

export type DeleteTagResponses = {
    /**
     * OK
     */
    200: ServerResponse;
};

export type DeleteTagResponse = DeleteTagResponses[keyof DeleteTagResponses];

export type FixTemplateMastersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/FixTemplateMasters';
};

export type FixTemplateMastersResponses = {
    /**
     * OK
     */
    200: number;
};

export type FixTemplateMastersResponse = FixTemplateMastersResponses[keyof FixTemplateMastersResponses];

export type GetApiControllersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetApiControllers';
};

export type GetApiControllersResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetApiControllersResponse = GetApiControllersResponses[keyof GetApiControllersResponses];

export type GetAssembliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetAssemblies';
};

export type GetAssembliesResponses = {
    /**
     * OK
     */
    200: Array<NameValue>;
};

export type GetAssembliesResponse = GetAssembliesResponses[keyof GetAssembliesResponses];

export type GetAssembliesWithInterfacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetAssembliesWithInterfaces';
};

export type GetAssembliesWithInterfacesResponses = {
    /**
     * OK
     */
    200: Array<NameValue>;
};

export type GetAssembliesWithInterfacesResponse = GetAssembliesWithInterfacesResponses[keyof GetAssembliesWithInterfacesResponses];

export type GetComposersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetComposers';
};

export type GetComposersResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetComposersResponse = GetComposersResponses[keyof GetComposersResponses];

export type GetCompositionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetCompositions';
};

export type GetCompositionsResponses = {
    /**
     * OK
     */
    200: Array<ContentTypeData>;
};

export type GetCompositionsResponse = GetCompositionsResponses[keyof GetCompositionsResponses];

export type GetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetConfig';
};

export type GetConfigResponses = {
    /**
     * OK
     */
    200: GodModeConfig;
};

export type GetConfigResponse = GetConfigResponses[keyof GetConfigResponses];

export type GetContentFindersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetContentFinders';
};

export type GetContentFindersResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetContentFindersResponse = GetContentFindersResponses[keyof GetContentFindersResponses];

export type GetContentPagedData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        name?: string;
        alias?: string;
        creatorId?: number;
        id?: string;
        level?: number;
        trashed?: boolean;
        updaterId?: number;
        languageId?: number;
        orderBy?: string;
    };
    url: '/umbraco/god-mode/api/v1/GetContentPaged';
};

export type GetContentPagedResponses = {
    /**
     * OK
     */
    200: Page1;
};

export type GetContentPagedResponse = GetContentPagedResponses[keyof GetContentPagedResponses];

export type GetContentTypeAliasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetContentTypeAliases';
};

export type GetContentTypeAliasesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetContentTypeAliasesResponse = GetContentTypeAliasesResponses[keyof GetContentTypeAliasesResponses];

export type GetContentTypeMapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetContentTypeMap';
};

export type GetContentTypeMapResponses = {
    /**
     * OK
     */
    200: Array<ContentTypeMap>;
};

export type GetContentTypeMapResponse = GetContentTypeMapResponses[keyof GetContentTypeMapResponses];

export type GetContentUsageDataData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
        orderBy?: string;
    };
    url: '/umbraco/god-mode/api/v1/GetContentUsageData';
};

export type GetContentUsageDataResponses = {
    /**
     * OK
     */
    200: Array<UsageModel>;
};

export type GetContentUsageDataResponse = GetContentUsageDataResponses[keyof GetContentUsageDataResponses];

export type GetDataTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetDataTypes';
};

export type GetDataTypesResponses = {
    /**
     * OK
     */
    200: Array<DataTypeMap>;
};

export type GetDataTypesResponse = GetDataTypesResponses[keyof GetDataTypesResponses];

export type GetDataTypesStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetDataTypesStatus';
};

export type GetDataTypesStatusResponses = {
    /**
     * OK
     */
    200: Array<DataTypeMap>;
};

export type GetDataTypesStatusResponse = GetDataTypesStatusResponses[keyof GetDataTypesStatusResponses];

export type GetEnvironmentDiagnosticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetEnvironmentDiagnostics';
};

export type GetEnvironmentDiagnosticsResponses = {
    /**
     * OK
     */
    200: Array<DiagnosticGroup>;
};

export type GetEnvironmentDiagnosticsResponse = GetEnvironmentDiagnosticsResponses[keyof GetEnvironmentDiagnosticsResponses];

export type GetInterfacesFromData = {
    body?: never;
    path?: never;
    query?: {
        assembly?: string;
    };
    url: '/umbraco/god-mode/api/v1/GetInterfacesFrom';
};

export type GetInterfacesFromResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetInterfacesFromResponse = GetInterfacesFromResponses[keyof GetInterfacesFromResponses];

export type GetLanguagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetLanguages';
};

export type GetLanguagesResponses = {
    /**
     * OK
     */
    200: Array<Lang>;
};

export type GetLanguagesResponse = GetLanguagesResponses[keyof GetLanguagesResponses];

export type GetMediaData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        name?: string;
        id?: number;
        mediaTypeId?: number;
        orderBy?: string;
        orderByDir?: string;
    };
    url: '/umbraco/god-mode/api/v1/GetMedia';
};

export type GetMediaResponses = {
    /**
     * OK
     */
    200: MediaMap;
};

export type GetMediaResponse = GetMediaResponses[keyof GetMediaResponses];

export type GetMediaTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetMediaTypes';
};

export type GetMediaTypesResponses = {
    /**
     * OK
     */
    200: Array<ItemBase>;
};

export type GetMediaTypesResponse = GetMediaTypesResponses[keyof GetMediaTypesResponses];

export type GetMemberGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetMemberGroups';
};

export type GetMemberGroupsResponses = {
    /**
     * OK
     */
    200: Array<MemberGroupModel>;
};

export type GetMemberGroupsResponse = GetMemberGroupsResponses[keyof GetMemberGroupsResponses];

export type GetMembersPagedData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
        groupId?: number;
        search?: string;
        orderBy?: string;
    };
    url: '/umbraco/god-mode/api/v1/GetMembersPaged';
};

export type GetMembersPagedResponses = {
    /**
     * OK
     */
    200: MemberModel;
};

export type GetMembersPagedResponse = GetMembersPagedResponses[keyof GetMembersPagedResponses];

export type GetNonMsAssembliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetNonMsAssemblies';
};

export type GetNonMsAssembliesResponses = {
    /**
     * OK
     */
    200: Array<NameValue>;
};

export type GetNonMsAssembliesResponse = GetNonMsAssembliesResponses[keyof GetNonMsAssembliesResponses];

export type GetNuCacheItemData = {
    body?: never;
    path?: never;
    query?: {
        id?: number;
    };
    url: '/umbraco/god-mode/api/v1/GetNuCacheItem';
};

export type GetNuCacheItemResponses = {
    /**
     * OK
     */
    200: NuCacheItem;
};

export type GetNuCacheItemResponse = GetNuCacheItemResponses[keyof GetNuCacheItemResponses];

export type GetNuCacheTypeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetNuCacheType';
};

export type GetNuCacheTypeResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetNuCacheTypeResponse = GetNuCacheTypeResponses[keyof GetNuCacheTypeResponses];

export type GetOrphanedTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetOrphanedTags';
};

export type GetOrphanedTagsResponses = {
    /**
     * OK
     */
    200: Array<Tag>;
};

export type GetOrphanedTagsResponse = GetOrphanedTagsResponses[keyof GetOrphanedTagsResponses];

export type GetPropertyEditorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetPropertyEditors';
};

export type GetPropertyEditorsResponses = {
    /**
     * OK
     */
    200: Array<DataTypeMap>;
};

export type GetPropertyEditorsResponse = GetPropertyEditorsResponses[keyof GetPropertyEditorsResponses];

export type GetPropertyGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetPropertyGroups';
};

export type GetPropertyGroupsResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetPropertyGroupsResponse = GetPropertyGroupsResponses[keyof GetPropertyGroupsResponses];

export type GetPropertyValueConvertersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetPropertyValueConverters';
};

export type GetPropertyValueConvertersResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetPropertyValueConvertersResponse = GetPropertyValueConvertersResponses[keyof GetPropertyValueConvertersResponses];

export type GetPublishedContentModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetPublishedContentModels';
};

export type GetPublishedContentModelsResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetPublishedContentModelsResponse = GetPublishedContentModelsResponses[keyof GetPublishedContentModelsResponses];

export type GetRegisteredServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetRegisteredServices';
};

export type GetRegisteredServicesResponses = {
    /**
     * OK
     */
    200: Array<RegisteredService>;
};

export type GetRegisteredServicesResponse = GetRegisteredServicesResponses[keyof GetRegisteredServicesResponses];

export type GetRenderMvcControllersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetRenderMvcControllers';
};

export type GetRenderMvcControllersResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetRenderMvcControllersResponse = GetRenderMvcControllersResponses[keyof GetRenderMvcControllersResponses];

export type GetStandardContentTypeAliasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetStandardContentTypeAliases';
};

export type GetStandardContentTypeAliasesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetStandardContentTypeAliasesResponse = GetStandardContentTypeAliasesResponses[keyof GetStandardContentTypeAliasesResponses];

export type GetSurfaceControllersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetSurfaceControllers';
};

export type GetSurfaceControllersResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetSurfaceControllersResponse = GetSurfaceControllersResponses[keyof GetSurfaceControllersResponses];

export type GetTagHelpersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetTagHelpers';
};

export type GetTagHelpersResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetTagHelpersResponse = GetTagHelpersResponses[keyof GetTagHelpersResponses];

export type GetTagMappingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetTagMapping';
};

export type GetTagMappingResponses = {
    /**
     * OK
     */
    200: Array<TagMapping>;
};

export type GetTagMappingResponse = GetTagMappingResponses[keyof GetTagMappingResponses];

export type GetTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetTemplates';
};

export type GetTemplatesResponses = {
    /**
     * OK
     */
    200: Array<TemplateModel>;
};

export type GetTemplatesResponse = GetTemplatesResponses[keyof GetTemplatesResponses];

export type GetTemplateUrlsToPingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetTemplateUrlsToPing';
};

export type GetTemplateUrlsToPingResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetTemplateUrlsToPingResponse = GetTemplateUrlsToPingResponses[keyof GetTemplateUrlsToPingResponses];

export type GetTypesAssignableFromData = {
    body?: never;
    path?: never;
    query?: {
        baseType?: string;
    };
    url: '/umbraco/god-mode/api/v1/GetTypesAssignableFrom';
};

export type GetTypesAssignableFromResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetTypesAssignableFromResponse = GetTypesAssignableFromResponses[keyof GetTypesAssignableFromResponses];

export type GetTypesFromData = {
    body?: never;
    path?: never;
    query?: {
        assembly?: string;
    };
    url: '/umbraco/god-mode/api/v1/GetTypesFrom';
};

export type GetTypesFromResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetTypesFromResponse = GetTypesFromResponses[keyof GetTypesFromResponses];

export type GetUmbracoAssembliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetUmbracoAssemblies';
};

export type GetUmbracoAssembliesResponses = {
    /**
     * OK
     */
    200: Array<NameValue>;
};

export type GetUmbracoAssembliesResponse = GetUmbracoAssembliesResponses[keyof GetUmbracoAssembliesResponses];

export type GetUrlProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetUrlProviders';
};

export type GetUrlProvidersResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetUrlProvidersResponse = GetUrlProvidersResponses[keyof GetUrlProvidersResponses];

export type GetUrlsToPingData = {
    body?: never;
    path?: never;
    query?: {
        culture?: string;
    };
    url: '/umbraco/god-mode/api/v1/GetUrlsToPing';
};

export type GetUrlsToPingResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetUrlsToPingResponse = GetUrlsToPingResponses[keyof GetUrlsToPingResponses];

export type GetViewComponentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/GetViewComponents';
};

export type GetViewComponentsResponses = {
    /**
     * OK
     */
    200: Array<TypeMap>;
};

export type GetViewComponentsResponse = GetViewComponentsResponses[keyof GetViewComponentsResponses];

export type PurgeMediaCacheData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/PurgeMediaCache';
};

export type PurgeMediaCacheResponses = {
    /**
     * OK
     */
    200: ServerResponse;
};

export type PurgeMediaCacheResponse = PurgeMediaCacheResponses[keyof PurgeMediaCacheResponses];

export type RestartAppPoolData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/god-mode/api/v1/RestartAppPool';
};

export type RestartAppPoolResponses = {
    /**
     * OK
     */
    200: ServerResponse;
};

export type RestartAppPoolResponse = RestartAppPoolResponses[keyof RestartAppPoolResponses];
